#!/usr/bin/env python3
"""Generate schemas/model_catalog.json from curated, vetted definitions."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src-tauri" / "schemas" / "model_catalog.json"

WAN_22_5B = "Wan-AI/Wan2.2-TI2V-5B-Diffusers"
WAN_22_T2V = "Wan-AI/Wan2.2-T2V-A14B-Diffusers"
WAN_22_I2V = "Wan-AI/Wan2.2-I2V-A14B-Diffusers"
WAN_21_14B = "Wan-AI/Wan2.1-T2V-14B"


def gguf(
    id: str,
    name: str,
    media: str,
    schema: str,
    desc: str,
    repo: str,
    file: str,
    size: float,
    vram: int,
    components: str | None = None,
    recommended: bool = False,
    tags: list[str] | None = None,
    variants: list[dict] | None = None,
) -> dict:
    entry = {
        "id": id,
        "name": name,
        "mediaType": media,
        "schemaId": schema,
        "description": desc,
        "sizeGb": size,
        "vramGb": vram,
        "minVramGb": vram,
        "recommended": recommended,
        "tags": tags or [],
        "downloadType": "gguf_bundle",
        "ggufRepo": repo,
        "ggufFile": file,
    }
    if components:
        entry["componentsRepo"] = components
    if variants:
        entry["quantVariants"] = variants
    return entry


def dual(
    id: str,
    name: str,
    schema: str,
    desc: str,
    repo: str,
    high: str,
    low: str,
    size: float,
    vram: int,
    components: str,
    recommended: bool = False,
    variants: list[dict] | None = None,
) -> dict:
    base_files = [high, low]
    entry = {
        "id": id,
        "name": name,
        "mediaType": "video",
        "schemaId": schema,
        "description": desc,
        "sizeGb": size,
        "vramGb": vram,
        "minVramGb": vram,
        "recommended": recommended,
        "tags": ["video", "gguf", "wan"],
        "downloadType": "gguf_bundle_dual",
        "ggufRepo": repo,
        "ggufFiles": base_files,
        "componentsRepo": components,
    }
    if variants:
        entry["quantVariants"] = variants
    return entry


def diffusers(
    id: str,
    name: str,
    media: str,
    schema: str,
    desc: str,
    repo: str,
    size: float,
    vram: int,
    recommended: bool = False,
    tags: list[str] | None = None,
) -> dict:
    return {
        "id": id,
        "name": name,
        "mediaType": media,
        "schemaId": schema,
        "description": desc,
        "sizeGb": size,
        "vramGb": vram,
        "minVramGb": vram,
        "recommended": recommended,
        "tags": tags or [],
        "downloadType": "diffusers",
        "hfRepo": repo,
    }


ENTRIES = [
    # ── WAN 2.2 video ──
    gguf(
        "wan-22-5b-video",
        "WAN 2.2 TI2V 5B",
        "video",
        "wan-2.2-5b",
        "Best 4GB starter. Text + image-to-video in one GGUF.",
        "QuantStack/Wan2.2-TI2V-5B-GGUF",
        "Wan2.2-TI2V-5B-Q4_K_S.gguf",
        3.1,
        4,
        WAN_22_5B,
        True,
        ["video", "gguf", "wan", "ti2v"],
        [
            {"id": "q3", "ggufFile": "Wan2.2-TI2V-5B-Q3_K_S.gguf", "sizeGb": 2.6, "vramGb": 4, "label": "Q3 (4GB)"},
            {"id": "q4", "ggufFile": "Wan2.2-TI2V-5B-Q4_K_S.gguf", "sizeGb": 3.1, "vramGb": 4, "label": "Q4 (4GB)"},
            {"id": "q5", "ggufFile": "Wan2.2-TI2V-5B-Q5_K_M.gguf", "sizeGb": 3.8, "vramGb": 6, "label": "Q5 (6GB)"},
        ],
    ),
    dual(
        "wan-22-a14b-t2v",
        "WAN 2.2 T2V A14B",
        "wan-2.2",
        "High-quality text-to-video. Downloads HighNoise + LowNoise pair.",
        "QuantStack/Wan2.2-T2V-A14B-GGUF",
        "HighNoise/Wan2.2-T2V-A14B-HighNoise-Q4_K_S.gguf",
        "LowNoise/Wan2.2-T2V-A14B-LowNoise-Q4_K_S.gguf",
        16.0,
        12,
        WAN_22_T2V,
        True,
        [
            {
                "id": "q3",
                "ggufFiles": [
                    "HighNoise/Wan2.2-T2V-A14B-HighNoise-Q3_K_S.gguf",
                    "LowNoise/Wan2.2-T2V-A14B-LowNoise-Q3_K_S.gguf",
                ],
                "sizeGb": 12.0,
                "vramGb": 10,
                "label": "Q3 (10GB)",
            },
            {
                "id": "q4",
                "ggufFiles": [
                    "HighNoise/Wan2.2-T2V-A14B-HighNoise-Q4_K_S.gguf",
                    "LowNoise/Wan2.2-T2V-A14B-LowNoise-Q4_K_S.gguf",
                ],
                "sizeGb": 16.0,
                "vramGb": 12,
                "label": "Q4 (12GB)",
            },
        ],
    ),
    dual(
        "wan-22-a14b-i2v",
        "WAN 2.2 I2V A14B",
        "wan-2.2",
        "Image-to-video at 14B quality. HighNoise + LowNoise pair.",
        "QuantStack/Wan2.2-I2V-A14B-GGUF",
        "HighNoise/Wan2.2-I2V-A14B-HighNoise-Q4_K_S.gguf",
        "LowNoise/Wan2.2-I2V-A14B-LowNoise-Q4_K_S.gguf",
        16.0,
        12,
        WAN_22_I2V,
        False,
        [
            {
                "id": "q4",
                "ggufFiles": [
                    "HighNoise/Wan2.2-I2V-A14B-HighNoise-Q4_K_S.gguf",
                    "LowNoise/Wan2.2-I2V-A14B-LowNoise-Q4_K_S.gguf",
                ],
                "sizeGb": 16.0,
                "vramGb": 12,
                "label": "Q4 (12GB)",
            }
        ],
    ),
    gguf(
        "wan-22-s2v-a14b",
        "WAN 2.2 S2V A14B",
        "video",
        "wan-2.2",
        "Sound/sync-to-video variant (single GGUF).",
        "QuantStack/Wan2.2-S2V-14B-GGUF",
        "Wan2.2-S2V-14B-Q4_K_S.gguf",
        9.0,
        12,
        WAN_22_T2V,
        False,
        ["video", "gguf", "wan"],
    ),
    dual(
        "wan-22-vace-a14b",
        "WAN 2.2 VACE A14B",
        "wan-2.2",
        "Video editing / VACE control model (14B).",
        "QuantStack/Wan2.2-VACE-Fun-A14B-GGUF",
        "HighNoise/Wan2.2-VACE-Fun-A14B-high-noise-Q4_K_S.gguf",
        "LowNoise/Wan2.2-VACE-Fun-A14B-low-noise-Q4_K_S.gguf",
        16.0,
        12,
        WAN_22_T2V,
    ),
    gguf(
        "wan-22-animate-a14b",
        "WAN 2.2 Animate A14B",
        "video",
        "wan-2.2",
        "Character animation / pose-driven video.",
        "QuantStack/Wan2.2-Animate-14B-GGUF",
        "Wan2.2-Animate-14B-Q4_K_S.gguf",
        9.0,
        12,
        WAN_22_T2V,
        False,
        ["video", "gguf", "wan"],
    ),
    # ── WAN 2.1 video ──
    diffusers(
        "wan-21-t2v-1.3b",
        "WAN 2.1 T2V 1.3B",
        "video",
        "wan-2.1",
        "Lightweight diffusers text-to-video.",
        "Wan-AI/Wan2.1-T2V-1.3B",
        5.0,
        6,
        False,
        ["video", "diffusers", "wan"],
    ),
    diffusers(
        "wan-21-t2v-14b",
        "WAN 2.1 T2V 14B",
        "video",
        "wan-2.1",
        "Full 14B WAN 2.1 text-to-video (diffusers).",
        "Wan-AI/Wan2.1-T2V-14B",
        28.0,
        16,
        False,
        ["video", "diffusers", "wan"],
    ),
    diffusers(
        "wan-21-i2v-14b-480p",
        "WAN 2.1 I2V 14B 480p",
        "video",
        "wan-2.1",
        "Image-to-video at 480p.",
        "Wan-AI/Wan2.1-I2V-14B-480P",
        28.0,
        16,
        False,
        ["video", "diffusers", "wan", "i2v"],
    ),
    diffusers(
        "wan-21-i2v-14b-720p",
        "WAN 2.1 I2V 14B 720p",
        "video",
        "wan-2.1",
        "Image-to-video at 720p.",
        "Wan-AI/Wan2.1-I2V-14B-720P",
        32.0,
        20,
        False,
        ["video", "diffusers", "wan", "i2v"],
    ),
    gguf(
        "wan-21-t2v-14b-gguf",
        "WAN 2.1 T2V 14B GGUF",
        "video",
        "wan-2.1",
        "Quantized WAN 2.1 14B text-to-video.",
        "city96/Wan2.1-T2V-14B-gguf",
        "wan2.1-t2v-14b-Q4_K_S.gguf",
        9.0,
        10,
        WAN_21_14B,
        False,
        ["video", "gguf", "wan"],
        [
            {"id": "q4", "ggufFile": "wan2.1-t2v-14b-Q4_K_S.gguf", "sizeGb": 9.0, "vramGb": 10, "label": "Q4 (10GB)"},
            {"id": "q5", "ggufFile": "wan2.1-t2v-14b-Q5_K_M.gguf", "sizeGb": 11.0, "vramGb": 12, "label": "Q5 (12GB)"},
        ],
    ),
    gguf(
        "wan-21-i2v-480-gguf",
        "WAN 2.1 I2V 480p GGUF",
        "video",
        "wan-2.1",
        "GGUF image-to-video at 480p.",
        "city96/Wan2.1-I2V-14B-480P-gguf",
        "wan2.1-i2v-14b-480p-Q4_K_S.gguf",
        9.0,
        10,
        "Wan-AI/Wan2.1-I2V-14B-480P",
        False,
        ["video", "gguf", "wan", "i2v"],
    ),
    gguf(
        "wan-21-i2v-720-gguf",
        "WAN 2.1 I2V 720p GGUF",
        "video",
        "wan-2.1",
        "GGUF image-to-video at 720p.",
        "city96/Wan2.1-I2V-14B-720P-gguf",
        "wan2.1-i2v-14b-720p-Q4_K_S.gguf",
        9.5,
        12,
        "Wan-AI/Wan2.1-I2V-14B-720P",
        False,
        ["video", "gguf", "wan", "i2v"],
    ),
    gguf(
        "wan-21-flf2v-720-gguf",
        "WAN 2.1 FLF2V 720p GGUF",
        "video",
        "wan-2.1",
        "First-last-frame to video at 720p.",
        "city96/Wan2.1-FLF2V-14B-720P-gguf",
        "wan2.1-flf2v-14b-720p-Q4_K_S.gguf",
        9.5,
        12,
        "Wan-AI/Wan2.1-FLF2V-14B-720P",
        False,
        ["video", "gguf", "wan"],
    ),
    # ── LTX video ──
    diffusers(
        "ltx-video-2b",
        "LTX Video 2B",
        "video",
        "ltx-video-2",
        "Lightricks LTX text-to-video (diffusers).",
        "Lightricks/LTX-Video",
        8.0,
        10,
        True,
        ["video", "diffusers", "ltx"],
    ),
    gguf(
        "ltx-video-gguf",
        "LTX Video 2B GGUF",
        "video",
        "ltx-video-2",
        "Quantized LTX video model.",
        "pollockjj/ltx-video-2b-v0.9.1-gguf",
        "ltx-video-2b-v0.9.1-Q4_K_S.gguf",
        1.8,
        8,
        "Lightricks/LTX-Video",
        False,
        ["video", "gguf", "ltx"],
    ),
    # ── Flux image ──
    gguf(
        "flux-schnell-gguf",
        "Flux Schnell",
        "image",
        "flux-schnell",
        "Fastest Flux images. Great for drafts.",
        "city96/FLUX.1-schnell-gguf",
        "flux1-schnell-Q4_K_S.gguf",
        6.5,
        6,
        "black-forest-labs/FLUX.1-schnell",
        True,
        ["image", "gguf", "flux"],
        [
            {"id": "q4", "ggufFile": "flux1-schnell-Q4_K_S.gguf", "sizeGb": 6.5, "vramGb": 6, "label": "Q4 (6GB)"},
            {"id": "q5", "ggufFile": "flux1-schnell-Q5_K_S.gguf", "sizeGb": 8.0, "vramGb": 8, "label": "Q5 (8GB)"},
        ],
    ),
    gguf(
        "flux-dev-gguf",
        "Flux Dev",
        "image",
        "flux-dev",
        "Higher quality Flux development model.",
        "city96/FLUX.1-dev-gguf",
        "flux1-dev-Q4_K_S.gguf",
        6.8,
        8,
        "black-forest-labs/FLUX.1-dev",
        True,
        ["image", "gguf", "flux"],
        [
            {"id": "q4", "ggufFile": "flux1-dev-Q4_K_S.gguf", "sizeGb": 6.8, "vramGb": 8, "label": "Q4 (8GB)"},
            {"id": "q5", "ggufFile": "flux1-dev-Q5_K_S.gguf", "sizeGb": 8.3, "vramGb": 10, "label": "Q5 (10GB)"},
        ],
    ),
    gguf(
        "flux-schnell-unsloth",
        "Flux Schnell (Unsloth)",
        "image",
        "flux-schnell",
        "Alternative Flux Schnell quantizations.",
        "unsloth/FLUX.1-schnell-GGUF",
        "flux1-schnell-Q4_K_S.gguf",
        6.5,
        6,
        "black-forest-labs/FLUX.1-schnell",
        False,
        ["image", "gguf", "flux"],
    ),
    gguf(
        "flux-klein-4b",
        "Flux Klein 4B",
        "image",
        "flux-schnell",
        "Compact Flux 2 Klein 4B GGUF.",
        "unsloth/FLUX.2-klein-4B-GGUF",
        "flux-2-klein-4b-Q4_K_S.gguf",
        3.2,
        6,
        "black-forest-labs/FLUX.1-schnell",
        False,
        ["image", "gguf", "flux"],
    ),
    gguf(
        "flux-klein-9b",
        "Flux Klein 9B",
        "image",
        "flux-dev",
        "Flux 2 Klein 9B GGUF.",
        "unsloth/FLUX.2-klein-9B-GGUF",
        "flux-2-klein-9b-Q4_K_S.gguf",
        6.0,
        8,
        "black-forest-labs/FLUX.1-dev",
        False,
        ["image", "gguf", "flux"],
    ),
    gguf(
        "flux-fill-dev-gguf",
        "Flux Fill Dev",
        "image",
        "flux-dev",
        "Inpainting / fill Flux Dev GGUF.",
        "YarvixPA/FLUX.1-Fill-dev-GGUF",
        "flux1-fill-dev-Q4_0.gguf",
        6.8,
        8,
        "black-forest-labs/FLUX.1-dev",
        False,
        ["image", "gguf", "flux"],
    ),
    # ── SDXL / SD image ──
    gguf(
        "sdxl-base-gguf",
        "SDXL Base",
        "image",
        "sdxl-base",
        "Classic SDXL in GGUF format.",
        "HyperX-Sentience/SDXL-GGUF",
        "sdxl_base_1.0_Q4_K_S.gguf",
        1.5,
        6,
        "stabilityai/stable-diffusion-xl-base-1.0",
        True,
        ["image", "gguf", "sdxl"],
        [
            {"id": "q4", "ggufFile": "sdxl_base_1.0_Q4_K_S.gguf", "sizeGb": 1.5, "vramGb": 6, "label": "Q4 (6GB)"},
            {"id": "q5", "ggufFile": "sd_xl_base_1.0_Q5_K_S.gguf", "sizeGb": 1.8, "vramGb": 8, "label": "Q5 (8GB)"},
        ],
    ),
    gguf(
        "sdxl-lightning-gguf",
        "SDXL Lightning",
        "image",
        "sdxl-base",
        "Few-step SDXL Lightning GGUF.",
        "mzwing/SDXL-Lightning-GGUF",
        "sdxl_lightning_2step.q4_0.gguf",
        1.6,
        6,
        "stabilityai/stable-diffusion-xl-base-1.0",
        False,
        ["image", "gguf", "sdxl"],
    ),
    gguf(
        "sdxl-turbo-gguf",
        "SDXL Turbo GGUF",
        "image",
        "z-image-turbo",
        "Ultra-fast SDXL turbo in GGUF.",
        "OlegSkutte/sdxl-turbo-GGUF",
        "sd_xl_turbo_1.0.q8_0.gguf",
        3.5,
        6,
        "stabilityai/sdxl-turbo",
        False,
        ["image", "gguf", "sdxl"],
    ),
    gguf(
        "sdxl-silveroxides-gguf",
        "SDXL (Silveroxides)",
        "image",
        "sdxl-base",
        "Community SDXL GGUF quantizations.",
        "silveroxides/sdxl-gguf",
        "NoobAI-XL-Epsilon-v1.1-unet-Q4_K_S.gguf",
        1.5,
        6,
        "stabilityai/stable-diffusion-xl-base-1.0",
        False,
        ["image", "gguf", "sdxl"],
    ),
    diffusers(
        "sdxl-turbo",
        "SDXL Turbo",
        "image",
        "z-image-turbo",
        "SDXL turbo diffusers (full folder).",
        "stabilityai/sdxl-turbo",
        7.0,
        8,
        False,
        ["image", "diffusers", "sdxl"],
    ),
    diffusers(
        "sdxl-base-full",
        "SDXL Base (full)",
        "image",
        "sdxl-base",
        "Full SDXL diffusers — best compatibility.",
        "stabilityai/stable-diffusion-xl-base-1.0",
        7.0,
        10,
        False,
        ["image", "diffusers", "sdxl"],
    ),
    diffusers(
        "sd-1-5",
        "Stable Diffusion 1.5",
        "image",
        "sdxl-base",
        "Legacy SD 1.5 — huge ecosystem of LoRAs.",
        "runwayml/stable-diffusion-v1-5",
        4.0,
        4,
        False,
        ["image", "diffusers", "sd"],
    ),
    diffusers(
        "sd-1-4",
        "Stable Diffusion 1.4",
        "image",
        "sdxl-base",
        "Original SD 1.4 base model.",
        "CompVis/stable-diffusion-v1-4",
        4.0,
        4,
        False,
        ["image", "diffusers", "sd"],
    ),
    gguf(
        "wan-21-fun-inp-gguf",
        "WAN 2.1 Fun InP GGUF",
        "video",
        "wan-2.1",
        "WAN Fun inpainting-to-video GGUF.",
        "city96/Wan2.1-Fun-14B-InP-gguf",
        "wan2.1-fun-14b-inp-Q4_0.gguf",
        9.0,
        10,
        "Wan-AI/Wan2.1-T2V-14B",
        False,
        ["video", "gguf", "wan"],
    ),
    gguf(
        "wan-21-fun-control-gguf",
        "WAN 2.1 Fun Control GGUF",
        "video",
        "wan-2.1",
        "Control-guided WAN 2.1 video GGUF.",
        "city96/Wan2.1-Fun-14B-Control-gguf",
        "wan2.1-fun-14b-control-Q4_0.gguf",
        9.0,
        10,
        "Wan-AI/Wan2.1-T2V-14B",
        False,
        ["video", "gguf", "wan"],
    ),
]


def main() -> None:
    OUT.write_text(json.dumps({"entries": ENTRIES}, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(ENTRIES)} entries to {OUT}")


if __name__ == "__main__":
    main()
